codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  status:
    project:
      default:
        target: 40%
        threshold: 1%
    patch:
      default:
        target: 40%
        threshold: 1%
  parsers:
    v1:
      include_full_missed_files: true
  range: '70...100'
  round: down
  precision: 2
ignore:
  - '**/dist/**/*'
  - '**/*.mock*'
  - '**/*.mock-data/*'
  - '**/*.data.*'
  - '**/node_modules/**/*'
  - '**/*.d.ts'
  - '**/tests/**/*.ts'
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/vitest.config.*'
  - '**/tsconfig.*.json'
  - '**/tsconfig.json'
  - '**/typedoc.json'
  - '**/*.md'
  - '**/LICENSE'
  - '**/*.json'

comment:
  layout: 'header, diff, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

bundle_analysis:
  status: 'informational'

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 40%
      - type: patch
        target: 40%
  individual_flags:
    - name: package-*
      paths:
        - packages/*/
      carryforward: true
      statuses:
        - type: project
          target: 40%
        - type: patch
          target: 40%
