packages:
  - 'packages/*'
  - 'packages/sdk-effects/*'
  - 'packages/utils/*'
  - '!**/test/**'
  - 'e2e/*'
  - tools/*
  - 'scratchpad'

catalog:
  '@reduxjs/toolkit': ^2.8.2
  immer: ^10.1.1

catalogs:
  effect:
    'effect': '^3.12.7'
    '@effect/language-service': '^0.23.0'
    '@effect/platform': '^0.84.9'
    '@effect/platform-node': '^0.85.14'
    '@effect/vitest': '^0.23.9'
    '@effect/cli': ^0.67.1
