packages:
  - 'packages/*'
  - 'packages/sdk-effects/*'
  - 'packages/utils/*'
  - '!**/test/**'
  - 'e2e/*'
  - tools/*
  - 'scratchpad'

catalog:
  '@reduxjs/toolkit': ^2.8.2
  immer: ^10.1.1
  msw: ^2.5.1
  vite: ^7.1.12
  typescript: ^5.9.3

catalogs:
  effect:
    'effect': '^3.17.2'
    '@effect/cli': '^0.69.0'
    '@effect/language-service': '^0.35.2'
    '@effect/platform': '^0.90.0'
    '@effect/platform-node': '0.94.2'
    '@effect/vitest': '^0.23.9'
    '@effect/opentelemetry': '^0.56.1'

  vitest:
    vitest: '^4.0.6'
    vitest-canvas-mock: '^0.3.3'
    '@vitest/coverage-v8': '^4.0.6'
    '@vitest/ui': '^4.0.6'

link-workspace-packages: true
strict-peer-dependencies: false
save-workspace-protocol: rolling
save-prefix: ''
