packages:
  - 'packages/*'
  - 'packages/sdk-effects/*'
  - 'packages/utils/*'
  - '!**/test/**'
  - 'e2e/*'
  - 'tools/*'
  - 'scratchpad'
catalog:
  '@reduxjs/toolkit': '^2.8.2'
  immer: '^10.1.1'
  msw: '^2.5.1'
catalogs:
  effect:
    effect: '^3.19.0'
    '@effect/cli': '^0.69.0'
    '@effect/language-service': '^0.35.2'
    '@effect/platform': '^0.90.0'
    '@effect/platform-node': '0.94.2'
    '@effect/vitest': '^0.27.0'
    '@effect/opentelemetry': '^0.56.1'
  vitest:
    vitest: '^3.2.0'
    '@vitest/coverage-v8': '^3.2.0'
    'vitest-canvas-mock': '^1.1.3'
  vite:
    vite: '^7.3.1'

link-workspace-packages: true
strict-peer-dependencies: false
save-workspace-protocol: 'rolling'
save-prefix: ''
