/*
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 */

/** @public */
export enum RecognizeErrorCode {
  SDK_ERROR = 'SDK_ERROR',
  SDK_NOT_CONFIGURED = 'SDK_NOT_CONFIGURED',
  SDK_CONFIGURATION_FAILED = 'SDK_CONFIGURATION_FAILED',
  SDK_LOGGING_NOT_CONFIGURED = 'SDK_LOGGING_NOT_CONFIGURED',
  SDK_LOGGING_CONFIGURATION_FAILED = 'SDK_LOGGING_CONFIGURATION_FAILED',
  SDK_STORAGE_ERROR = 'SDK_STORAGE_ERROR',
  SDK_USER_CANCELLED = 'SDK_USER_CANCELLED',
  SDK_NO_NETWORK_CONNECTION = 'SDK_NO_NETWORK_CONNECTION',
  SDK_DYNAMIC_LINKING_MALFORMED_PAYLOAD = 'SDK_DYNAMIC_LINKING_MALFORMED_PAYLOAD',
  SDK_ARTIFACT_RETRIEVE_FAILED = 'SDK_ARTIFACT_RETRIEVE_FAILED',
  SDK_ARTIFACT_RETRIEVE_FROM_CLIENT_STATE_FAILED = 'SDK_ARTIFACT_RETRIEVE_FROM_CLIENT_STATE_FAILED',
  SDK_WEB_SOCKET_ERROR = 'SDK_WEB_SOCKET_ERROR',
  SDK_TIMEOUT = 'SDK_TIMEOUT',
  SDK_WEB_ASSEMBLY_IMPORT_FAILED = 'SDK_WEB_ASSEMBLY_IMPORT_FAILED',
  SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED = 'SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED',
  SDK_WEB_ASSEMBLY_ERROR = 'SDK_WEB_ASSEMBLY_ERROR',
  CAMERA_ERROR = 'CAMERA_ERROR',
  CAMERA_MISSING = 'CAMERA_MISSING',
  CAMERA_PERMISSION_DENIED = 'CAMERA_PERMISSION_DENIED',
  CAMERA_NOT_SUPPORTED = 'CAMERA_NOT_SUPPORTED',
  CORE_ERROR = 'CORE_ERROR',
  CORE_CUSTOMER_NOT_FOUND = 'CORE_CUSTOMER_NOT_FOUND',
  CORE_INVALID_API_KEY = 'CORE_INVALID_API_KEY',
  CORE_NOT_ENOUGH_API_KEY_SEATS = 'CORE_NOT_ENOUGH_API_KEY_SEATS',
  CORE_USER_NOT_ENROLLED = 'CORE_USER_NOT_ENROLLED',
  CORE_USER_ALREADY_ENROLLED = 'CORE_USER_ALREADY_ENROLLED',
  CORE_NOT_ENOUGH_CIRCUITS = 'CORE_NOT_ENOUGH_CIRCUITS',
  CORE_USER_LOCKED_OUT = 'CORE_USER_LOCKED_OUT',
  CORE_FACE_NOT_MATCHING = 'CORE_FACE_NOT_MATCHING',
  CORE_SECRET_NOT_FOUND = 'CORE_SECRET_NOT_FOUND',
  BIOM_ERROR = 'BIOM_ERROR',
  BIOM_REJECTED = 'BIOM_REJECTED',
  BIOM_SPOOFING = 'BIOM_SPOOFING',
  BIOM_DEVICE_ENVIRONMENT_AWARE_NOT_SUPPORTED = 'BIOM_DEVICE_ENVIRONMENT_AWARE_NOT_SUPPORTED',
  BIOM_LIVENESS_ENVIRONMENT_AWARE_NOT_SUPPORTED = 'BIOM_LIVENESS_ENVIRONMENT_AWARE_NOT_SUPPORTED',
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_AUTHORIZATION_FAILED = 'SERVER_AUTHORIZATION_FAILED',
  SERVER_ENCRYPTION_FAILED = 'SERVER_ENCRYPTION_FAILED',
  SERVER_RECOGNITION_FAILED = 'SERVER_RECOGNITION_FAILED',
  SERVER_TIMEOUT = 'SERVER_TIMEOUT',
  SECURITY_ERROR = 'SECURITY_ERROR',
  SECURITY_APPLICATION_EXPIRED = 'SECURITY_APPLICATION_EXPIRED',
  SECURITY_DEVICE_NOT_GENUINE = 'SECURITY_DEVICE_NOT_GENUINE',
  ALREADY_INITIALIZED = 'ALREADY_INITIALIZED',
  INVALID_ELEMENT = 'INVALID_ELEMENT',
}

/** @public */
export interface RecognizeError extends Error {
  code: RecognizeErrorCode;
  cause?: unknown;
}

/** @public */
export const createRecognizeError = (code: RecognizeErrorCode, cause?: unknown): RecognizeError => {
  const error = new Error(code) as RecognizeError;
  error.name = 'RecognizeError';
  error.code = code;
  if (cause !== undefined) error.cause = cause;
  return error;
};

const webErrorsMap: Record<string, RecognizeErrorCode> = {
  FRAME_RESULTS_SET_UNSET: RecognizeErrorCode.SDK_ERROR,
  OPTIONS_UNSET: RecognizeErrorCode.SDK_ERROR,
  VIDEO_ELEMENT_UNSET: RecognizeErrorCode.SDK_ERROR,
  VIDEO_ELEMENT_EVENT_LISTENERS_UNSET: RecognizeErrorCode.SDK_ERROR,
  WEB_SOCKET_MESSAGE_SET_UNSET: RecognizeErrorCode.SDK_ERROR,
  MEDIA_DEVICES_EMPTY_AUDIO_INPUT_LABEL: RecognizeErrorCode.SDK_ERROR,
  MEDIA_DEVICES_EMPTY_VIDEO_INPUT_LABEL: RecognizeErrorCode.CAMERA_PERMISSION_DENIED,
  MEDIA_DEVICES_NO_VIDEO_INPUTS: RecognizeErrorCode.CAMERA_MISSING,
  MEDIA_STREAM_ABORT: RecognizeErrorCode.CAMERA_ERROR,
  MEDIA_STREAM_INVALID_STATE: RecognizeErrorCode.CAMERA_ERROR,
  MEDIA_STREAM_NOT_ALLOWED: RecognizeErrorCode.CAMERA_PERMISSION_DENIED,
  MEDIA_STREAM_NOT_FOUND: RecognizeErrorCode.CAMERA_ERROR,
  MEDIA_STREAM_NOT_READABLE: RecognizeErrorCode.CAMERA_ERROR,
  MEDIA_STREAM_OVERCONSTRAINED: RecognizeErrorCode.CAMERA_NOT_SUPPORTED,
  MEDIA_STREAM_SECURITY: RecognizeErrorCode.CAMERA_ERROR,
  MEDIA_STREAM_TYPE: RecognizeErrorCode.CAMERA_ERROR,
  MEDIA_STREAM_UNSET: RecognizeErrorCode.CAMERA_ERROR,
  SERVER_CUSTOMER_NOT_FOUND: RecognizeErrorCode.CORE_CUSTOMER_NOT_FOUND,
  SERVER_FACE_DOES_NOT_MATCH: RecognizeErrorCode.CORE_FACE_NOT_MATCHING,
  SERVER_FORBIDDEN: RecognizeErrorCode.SERVER_AUTHORIZATION_FAILED,
  SERVER_IMAGE_ENCRYPT_FAILED: RecognizeErrorCode.SERVER_ENCRYPTION_FAILED,
  SERVER_INTERNAL_ERROR: RecognizeErrorCode.SERVER_ERROR,
  SERVER_NO_ATTEMPTS_LEFT: RecognizeErrorCode.CORE_NOT_ENOUGH_CIRCUITS,
  SERVER_RECOGNITION_FAILED: RecognizeErrorCode.SERVER_RECOGNITION_FAILED,
  SERVER_TIMEOUT: RecognizeErrorCode.SERVER_TIMEOUT,
  SERVER_UNAVAILABLE_SERVICE: RecognizeErrorCode.SERVER_ERROR,
  SERVER_UNPROCESSABLE_EVENT: RecognizeErrorCode.SERVER_ERROR,
  SERVER_USER_ALREADY_ENROLLED: RecognizeErrorCode.CORE_USER_ALREADY_ENROLLED,
  SERVER_USER_NOT_FOUND: RecognizeErrorCode.CORE_USER_NOT_ENROLLED,
  SERVER_USER_LOCKED_OUT: RecognizeErrorCode.CORE_USER_LOCKED_OUT,
  SERVER_VALIDATION_FAILED: RecognizeErrorCode.SERVER_ERROR,
  SESSION_MANAGER_NOT_NULL: RecognizeErrorCode.SDK_ERROR,
  SESSION_MANAGER_NULL: RecognizeErrorCode.SDK_ERROR,
  CREATE_MEDIA_STREAM_ARGS_UNSET: RecognizeErrorCode.SDK_ERROR,
  EXCEPTION: RecognizeErrorCode.SDK_ERROR,
  RUNTIME_VIOLATION: RecognizeErrorCode.SECURITY_ERROR,
  SYMBOL_DESCRIPTION_UNSET: RecognizeErrorCode.SDK_ERROR,
  SESSION_ID_UNSET: RecognizeErrorCode.SDK_ERROR,
  CUSTOMER_UNSET: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  KEY_DECODE_FAILED: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  KEY_UNSET: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  KEY_ID_UNSET: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  USERNAME_UNSET: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  WEB_SOCKET_URL_PARSE_FAILED: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  WEB_SOCKET_URL_UNSET: RecognizeErrorCode.SDK_CONFIGURATION_FAILED,
  WEB_ASSEMBLY_ABORTED: RecognizeErrorCode.SDK_WEB_ASSEMBLY_ERROR,
  WEB_ASSEMBLY_FACTORY_FAILED: RecognizeErrorCode.SDK_WEB_ASSEMBLY_ERROR,
  WEB_ASSEMBLY_IMPORT_FAILED: RecognizeErrorCode.SDK_WEB_ASSEMBLY_IMPORT_FAILED,
  WEB_ASSEMBLY_NOT_READY: RecognizeErrorCode.SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED,
  WEB_ASSEMBLY_MODULE_NOT_FOUND: RecognizeErrorCode.SDK_WEB_ASSEMBLY_ERROR,
  WEB_SOCKET_ERROR: RecognizeErrorCode.SDK_WEB_SOCKET_ERROR,
  WEB_SOCKET_OPEN: RecognizeErrorCode.SDK_WEB_SOCKET_ERROR,
  WEB_SOCKET_TIMEOUT: RecognizeErrorCode.SDK_TIMEOUT,
  WEB_SOCKET_UNEXPECTED_CLOSE: RecognizeErrorCode.SDK_WEB_SOCKET_ERROR,
  QUEUE_UNSET: RecognizeErrorCode.SDK_ERROR,
  SYMBOL_UNSET: RecognizeErrorCode.SDK_ERROR,
  NONCANCELABLE: RecognizeErrorCode.SDK_ERROR,
};

export const mapWebError = (reason: string | undefined): RecognizeErrorCode =>
  (reason && webErrorsMap[reason]) || RecognizeErrorCode.SDK_ERROR;
