services:
  https-proxy:
    build:
      context: ./https-proxy
    image: ping-local-https
    ports:
      - '8443:8443'
    environment:
      LISTEN_PORT: 8443
      SSL_CERT_PATH: /etc/nginx/tls/proxy-cert.pem
      SSL_CERT_KEY_PATH: /etc/nginx/tls/proxy-key.pem
      DAVINCI_UPSTREAM: host.docker.internal:5829
      OIDC_UPSTREAM: host.docker.internal:5173
      PROTECT_UPSTREAM: host.docker.internal:4300
      DEVICE_UPSTREAM: host.docker.internal:4301
      MOCK_API_UPSTREAM: host.docker.internal:9443
    volumes:
      - ./certs:/etc/nginx/tls:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
