/*
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 */

import type { RecognizeErrorCodeValue } from '../recognize.types.js';
import { RECOGNIZE_ERROR_CODE } from './recognize-error-code.js';

export const RECOGNIZE_SDK_TO_RECOGNIZE_PROXY_ERROR_MAP: Record<string, RecognizeErrorCodeValue> =
  Object.freeze({
    FRAME_RESULTS_SET_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    OPTIONS_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    USER_LOCKOUT_EXPIRATION_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    VIDEO_ELEMENT_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    MEDIA_DEVICES_EMPTY_AUDIO_INPUT_LABEL: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    MEDIA_DEVICES_EMPTY_VIDEO_INPUT_LABEL: RECOGNIZE_ERROR_CODE.CAMERA_PERMISSION_DENIED,
    MEDIA_DEVICES_NO_VIDEO_INPUTS: RECOGNIZE_ERROR_CODE.CAMERA_NOT_FOUND,
    MEDIA_STREAM_ABORT: RECOGNIZE_ERROR_CODE.CAMERA_ERROR,
    MEDIA_STREAM_INVALID_STATE: RECOGNIZE_ERROR_CODE.CAMERA_ERROR,
    MEDIA_STREAM_NOT_ALLOWED: RECOGNIZE_ERROR_CODE.CAMERA_PERMISSION_DENIED,
    MEDIA_STREAM_NOT_FOUND: RECOGNIZE_ERROR_CODE.CAMERA_ERROR,
    MEDIA_STREAM_NOT_READABLE: RECOGNIZE_ERROR_CODE.CAMERA_ERROR,
    MEDIA_STREAM_OVERCONSTRAINED: RECOGNIZE_ERROR_CODE.CAMERA_NOT_SUPPORTED,
    MEDIA_STREAM_SECURITY: RECOGNIZE_ERROR_CODE.CAMERA_ERROR,
    MEDIA_STREAM_TYPE: RECOGNIZE_ERROR_CODE.CAMERA_ERROR,
    SERVER_CUSTOMER_NOT_FOUND: RECOGNIZE_ERROR_CODE.CORE_CUSTOMER_NOT_FOUND,
    SERVER_FORBIDDEN: RECOGNIZE_ERROR_CODE.SERVER_AUTHORIZATION_FAILED,
    SERVER_INTERNAL_ERROR: RECOGNIZE_ERROR_CODE.SERVER_ERROR,
    SERVER_INVALID_REQUEST: RECOGNIZE_ERROR_CODE.SERVER_ERROR,
    SERVER_INVALID_RESPONSE: RECOGNIZE_ERROR_CODE.SERVER_ERROR,
    SERVER_INVALID_STATE: RECOGNIZE_ERROR_CODE.SERVER_ERROR,
    SERVER_NO_ATTEMPTS_LEFT: RECOGNIZE_ERROR_CODE.CORE_NOT_ENOUGH_CIRCUITS,
    SERVER_RECOGNITION_FAILED: RECOGNIZE_ERROR_CODE.SERVER_RECOGNITION_FAILED,
    SERVER_USER_LOCKED_OUT: RECOGNIZE_ERROR_CODE.CORE_USER_LOCKED_OUT,
    SESSION_DATABASE_ERROR: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    SESSION_MANAGER_NOT_NULL: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    SESSION_MANAGER_NULL: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    SESSION_MEDIA_STREAM_TIMEOUT: RECOGNIZE_ERROR_CODE.SDK_TIMEOUT,
    SESSION_MEDIA_STREAM_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    CREATE_MEDIA_STREAM_ARGS_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    EXCEPTION: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    GET_VIDEO_MEDIA_DEVICES_ARGS_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    RUNTIME_VIOLATION: RECOGNIZE_ERROR_CODE.SECURITY_ERROR,
    SYMBOL_DESCRIPTION_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    CUSTOMER_UNSET: RECOGNIZE_ERROR_CODE.SDK_INVALID_CONFIGURATION,
    SERVICE_URL_PARSE_FAILED: RECOGNIZE_ERROR_CODE.SDK_INVALID_CONFIGURATION,
    SERVICE_URL_UNSET: RECOGNIZE_ERROR_CODE.SDK_INVALID_CONFIGURATION,
    USERNAME_UNSET: RECOGNIZE_ERROR_CODE.SDK_INVALID_CONFIGURATION,
    WEB_ASSEMBLY_ABORTED: RECOGNIZE_ERROR_CODE.SDK_WEB_ASSEMBLY_ERROR,
    WEB_ASSEMBLY_FACTORY_FAILED: RECOGNIZE_ERROR_CODE.SDK_WEB_ASSEMBLY_ERROR,
    WEB_ASSEMBLY_IMPORT_FAILED: RECOGNIZE_ERROR_CODE.SDK_WEB_ASSEMBLY_IMPORT_FAILED,
    WEB_ASSEMBLY_NOT_READY: RECOGNIZE_ERROR_CODE.SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED,
    WEB_ASSEMBLY_MODULE_NOT_FOUND: RECOGNIZE_ERROR_CODE.SDK_WEB_ASSEMBLY_ERROR,
    SLUG_UNSUPPORTED: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    QUEUE_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
    SYMBOL_UNSET: RECOGNIZE_ERROR_CODE.SDK_ERROR,
  });
