/*
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 */

/** @public */
export enum RecognizeErrorCode {
  SDK_ERROR = 'SDK_ERROR',
  SDK_NOT_CONFIGURED = 'SDK_NOT_CONFIGURED',
  SDK_CONFIGURATION_FAILED = 'SDK_CONFIGURATION_FAILED',
  SDK_LOGGING_NOT_CONFIGURED = 'SDK_LOGGING_NOT_CONFIGURED',
  SDK_LOGGING_CONFIGURATION_FAILED = 'SDK_LOGGING_CONFIGURATION_FAILED',
  SDK_STORAGE_ERROR = 'SDK_STORAGE_ERROR',
  SDK_USER_CANCELLED = 'SDK_USER_CANCELLED',
  SDK_NO_NETWORK_CONNECTION = 'SDK_NO_NETWORK_CONNECTION',
  SDK_DYNAMIC_LINKING_MALFORMED_PAYLOAD = 'SDK_DYNAMIC_LINKING_MALFORMED_PAYLOAD',
  SDK_ARTIFACT_RETRIEVE_FAILED = 'SDK_ARTIFACT_RETRIEVE_FAILED',
  SDK_ARTIFACT_RETRIEVE_FROM_CLIENT_STATE_FAILED = 'SDK_ARTIFACT_RETRIEVE_FROM_CLIENT_STATE_FAILED',
  SDK_WEB_SOCKET_ERROR = 'SDK_WEB_SOCKET_ERROR',
  SDK_TIMEOUT = 'SDK_TIMEOUT',
  SDK_WEB_ASSEMBLY_IMPORT_FAILED = 'SDK_WEB_ASSEMBLY_IMPORT_FAILED',
  SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED = 'SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED',
  SDK_WEB_ASSEMBLY_ERROR = 'SDK_WEB_ASSEMBLY_ERROR',
  CAMERA_ERROR = 'CAMERA_ERROR',
  CAMERA_MISSING = 'CAMERA_MISSING',
  CAMERA_PERMISSION_DENIED = 'CAMERA_PERMISSION_DENIED',
  CAMERA_NOT_SUPPORTED = 'CAMERA_NOT_SUPPORTED',
  CORE_ERROR = 'CORE_ERROR',
  CORE_CUSTOMER_NOT_FOUND = 'CORE_CUSTOMER_NOT_FOUND',
  CORE_INVALID_API_KEY = 'CORE_INVALID_API_KEY',
  CORE_NOT_ENOUGH_API_KEY_SEATS = 'CORE_NOT_ENOUGH_API_KEY_SEATS',
  CORE_USER_NOT_ENROLLED = 'CORE_USER_NOT_ENROLLED',
  CORE_USER_ALREADY_ENROLLED = 'CORE_USER_ALREADY_ENROLLED',
  CORE_NOT_ENOUGH_CIRCUITS = 'CORE_NOT_ENOUGH_CIRCUITS',
  CORE_USER_LOCKED_OUT = 'CORE_USER_LOCKED_OUT',
  CORE_FACE_NOT_MATCHING = 'CORE_FACE_NOT_MATCHING',
  CORE_SECRET_NOT_FOUND = 'CORE_SECRET_NOT_FOUND',
  BIOM_ERROR = 'BIOM_ERROR',
  BIOM_REJECTED = 'BIOM_REJECTED',
  BIOM_SPOOFING = 'BIOM_SPOOFING',
  BIOM_DEVICE_ENVIRONMENT_AWARE_NOT_SUPPORTED = 'BIOM_DEVICE_ENVIRONMENT_AWARE_NOT_SUPPORTED',
  BIOM_LIVENESS_ENVIRONMENT_AWARE_NOT_SUPPORTED = 'BIOM_LIVENESS_ENVIRONMENT_AWARE_NOT_SUPPORTED',
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_AUTHORIZATION_FAILED = 'SERVER_AUTHORIZATION_FAILED',
  SERVER_ENCRYPTION_FAILED = 'SERVER_ENCRYPTION_FAILED',
  SERVER_RECOGNITION_FAILED = 'SERVER_RECOGNITION_FAILED',
  SERVER_TIMEOUT = 'SERVER_TIMEOUT',
  SECURITY_ERROR = 'SECURITY_ERROR',
  SECURITY_APPLICATION_EXPIRED = 'SECURITY_APPLICATION_EXPIRED',
  SECURITY_DEVICE_NOT_GENUINE = 'SECURITY_DEVICE_NOT_GENUINE',
}
