/*
 *
 * Copyright © 2026 Ping Identity Corporation. All right reserved.
 *
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 *
 */

import type { RecognizeErrorCodeValue } from '../recognize.types.js';
import { RecognizeErrorCode } from './recognize-error-code.js';

export const RECOGNIZE_SDK_TO_RECOGNIZE_PROXY_ERROR_MAP: Record<string, RecognizeErrorCodeValue> =
  Object.freeze({
    FRAME_RESULTS_SET_UNSET: RecognizeErrorCode.SDK_ERROR,
    OPTIONS_UNSET: RecognizeErrorCode.SDK_ERROR,
    USER_LOCKOUT_EXPIRATION_UNSET: RecognizeErrorCode.SDK_ERROR,
    VIDEO_ELEMENT_UNSET: RecognizeErrorCode.SDK_ERROR,
    MEDIA_DEVICES_EMPTY_AUDIO_INPUT_LABEL: RecognizeErrorCode.SDK_ERROR,
    MEDIA_DEVICES_EMPTY_VIDEO_INPUT_LABEL: RecognizeErrorCode.CAMERA_PERMISSION_DENIED,
    MEDIA_DEVICES_NO_VIDEO_INPUTS: RecognizeErrorCode.CAMERA_NOT_FOUND,
    MEDIA_STREAM_ABORT: RecognizeErrorCode.CAMERA_ERROR,
    MEDIA_STREAM_INVALID_STATE: RecognizeErrorCode.CAMERA_ERROR,
    MEDIA_STREAM_NOT_ALLOWED: RecognizeErrorCode.CAMERA_PERMISSION_DENIED,
    MEDIA_STREAM_NOT_FOUND: RecognizeErrorCode.CAMERA_ERROR,
    MEDIA_STREAM_NOT_READABLE: RecognizeErrorCode.CAMERA_ERROR,
    MEDIA_STREAM_OVERCONSTRAINED: RecognizeErrorCode.CAMERA_NOT_SUPPORTED,
    MEDIA_STREAM_SECURITY: RecognizeErrorCode.CAMERA_ERROR,
    MEDIA_STREAM_TYPE: RecognizeErrorCode.CAMERA_ERROR,
    SERVER_CUSTOMER_NOT_FOUND: RecognizeErrorCode.CORE_CUSTOMER_NOT_FOUND,
    SERVER_FORBIDDEN: RecognizeErrorCode.SERVER_AUTHORIZATION_FAILED,
    SERVER_INTERNAL_ERROR: RecognizeErrorCode.SERVER_ERROR,
    SERVER_INVALID_REQUEST: RecognizeErrorCode.SERVER_ERROR,
    SERVER_INVALID_RESPONSE: RecognizeErrorCode.SERVER_ERROR,
    SERVER_INVALID_STATE: RecognizeErrorCode.SERVER_ERROR,
    SERVER_NO_ATTEMPTS_LEFT: RecognizeErrorCode.CORE_NOT_ENOUGH_CIRCUITS,
    SERVER_RECOGNITION_FAILED: RecognizeErrorCode.SERVER_RECOGNITION_FAILED,
    SERVER_USER_LOCKED_OUT: RecognizeErrorCode.CORE_USER_LOCKED_OUT,
    SESSION_DATABASE_ERROR: RecognizeErrorCode.SDK_ERROR,
    SESSION_MANAGER_NOT_NULL: RecognizeErrorCode.SDK_ERROR,
    SESSION_MANAGER_NULL: RecognizeErrorCode.SDK_ERROR,
    SESSION_MEDIA_STREAM_TIMEOUT: RecognizeErrorCode.SDK_TIMEOUT,
    SESSION_MEDIA_STREAM_UNSET: RecognizeErrorCode.SDK_ERROR,
    CREATE_MEDIA_STREAM_ARGS_UNSET: RecognizeErrorCode.SDK_ERROR,
    EXCEPTION: RecognizeErrorCode.SDK_ERROR,
    GET_VIDEO_MEDIA_DEVICES_ARGS_UNSET: RecognizeErrorCode.SDK_ERROR,
    RUNTIME_VIOLATION: RecognizeErrorCode.SECURITY_ERROR,
    SYMBOL_DESCRIPTION_UNSET: RecognizeErrorCode.SDK_ERROR,
    CUSTOMER_UNSET: RecognizeErrorCode.SDK_INVALID_CONFIGURATION,
    SERVICE_URL_PARSE_FAILED: RecognizeErrorCode.SDK_INVALID_CONFIGURATION,
    SERVICE_URL_UNSET: RecognizeErrorCode.SDK_INVALID_CONFIGURATION,
    USERNAME_UNSET: RecognizeErrorCode.SDK_INVALID_CONFIGURATION,
    WEB_ASSEMBLY_ABORTED: RecognizeErrorCode.SDK_WEB_ASSEMBLY_ERROR,
    WEB_ASSEMBLY_FACTORY_FAILED: RecognizeErrorCode.SDK_WEB_ASSEMBLY_ERROR,
    WEB_ASSEMBLY_IMPORT_FAILED: RecognizeErrorCode.SDK_WEB_ASSEMBLY_IMPORT_FAILED,
    WEB_ASSEMBLY_NOT_READY: RecognizeErrorCode.SDK_WEB_ASSEMBLY_IMPORT_NOT_FULFILLED,
    WEB_ASSEMBLY_MODULE_NOT_FOUND: RecognizeErrorCode.SDK_WEB_ASSEMBLY_ERROR,
    SLUG_UNSUPPORTED: RecognizeErrorCode.SDK_ERROR,
    QUEUE_UNSET: RecognizeErrorCode.SDK_ERROR,
    SYMBOL_UNSET: RecognizeErrorCode.SDK_ERROR,
  });
