name: ForgeRock Pull Request CI
on:
  pull_request:

env:
  NX_CLOUD_ENCRYPTION_KEY: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.PR_NX_CLOUD_ACCESS_TOKEN }} # Read Only
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CI: true

# recommended to set a concurrency group
concurrency:
  group: preview-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        id: cache
        with:
          node-version: '22.14.0'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      - run: pnpm dlx nx-cloud start-ci-run --distribute-on=".nx/workflows/dynamic-changesets.yml" --stop-agents-after="e2e-ci" --with-env-vars="CODECOV_TOKEN"
      - run: pnpm nx sync:check

      - run: pnpm exec playwright install

      - uses: nrwl/nx-set-shas@v4
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - run: pnpm exec nx-cloud record -- nx format:check
      - run: pnpm exec nx affected -t build typecheck lint test e2e-ci

      - uses: codecov/codecov-action@v5
        with:
          files: ./packages/**/coverage/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: |
            ./**/.playwright/**
          retention-days: 30

      - name: build docs
        run: pnpm typedoc

      - name: preview-docs
        uses: rajyan/preview-pages@v1
        with:
          source-dir: docs
          pr-comment: 'none'

      - name: Update comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: Deployed ${{ github.sha }} to https://ForgeRock.github.io/ping-javascript-sdk/pr-${{ github.event.number }}/${{github.sha}} branch gh-pages in ForgeRock/ping-javascript-sdk
