name: Snapshots
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish from'
        required: false
        default: 'main'
        type: string

jobs:
  call-trusted-publish:
    name: Call trusted publish (beta dist-tag)
    uses: ./.github/workflows/publish.yml
    with:
      branch: ${{ inputs.branch }}
      dist_tag: beta
      prerelease: beta
      access: public
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
